### ISSUE TITLE
What about using tauri?

### ISSUE THREAD

**Issue by Terisback** [hex2f/OpenDiscord#1]
Cool webview alternative to reuse existing browser and memory for opendiscord
https://tauri.app/

**Comment by adntaha** [comment]
I think the goal is to be as close as possible to Discord, and since the Discord client doesn't use Tauri I don't see a point in doing so.

**Comment by Terisback** [comment]
do not agree

**Comment by hex2f** [comment]
I simply just don't have any experience using tauri, from what I understand it uses rust? Which is a language im not particularly good with :p

And as @botatooo said, the goal of this project is not really to create a better Discord client, but to be an as-close-as-possible recreation of Discord where people can play around with implementing feature ideas without breaking TOS.

**Comment by Terisback** [comment]
Tauri as ease as embedded into application with os access api web app.

Okay, undestandable.
